### ISSUE TITLE
Include and Filters no longer work

### ISSUE THREAD

**Issue by floriank** [contentful-labs/contentful.ex#20]
I received a tweet to the release of `v0.2.0` from @hukl that rightfully askes for the `filter` and `include` options originally present in `v0.1.1`:

```elixir
# v0.0.1
entries = Contentful.Delivery.entries(space_id, access_token, %{
    "content_type" => "categoryList",
    "include" => 2
})

# v0.2.0
entries = Contentful.Delivery.Entries.fetch_all([], space, "master", access_token)
```

I carelessly dropped this feature and it needs to be readded in a compatible fashion.

- [Original tweet](https://twitter.com/hukl/status/1252212797573914625)

**Comment by hukl** [comment]
Wow - top user support ;)
