### ISSUE TITLE
Upgrade code coverage

### ISSUE THREAD

**Issue by floriank** [contentful-labs/contentful.ex#24]
* [ ] Push code coverage by tests higher, ideally to something like 85% or above
* [x] Bonus points for `excoveralls` integration and displaying the percentage somewhere - has been done in the context of of #27

**Comment by asaaki** [comment]
Currently we're at 79 %. That's just 6 % below the ideal threshold.
Do we still want to push it further, or are we actually fine with the current coverage?

**Comment by floriank** [comment]
I think it's actually fine as is, it just should not go down from here.

**Comment by floriank** [comment]
I will probably continue to upgrade it over time anyway.

I'd say let's close this issue if nobody objects.
