### ISSUE TITLE
Contentful.SysData missing important information

### ISSUE THREAD

**Issue by OldhamMade** [contentful-labs/contentful.ex#44]
In previous versions, the map that has been replaced with `Contentful.SysData` contained a number of important fields. These included:

```elixir
...
  sys: %{
    contentType: %{
      sys: %{
        id: "<content-type-from-model>",  # for example: "author"
        ...
      }
    },
    createdAt: "<created-timestamp>",
    updatedAt: "<updated-timestamp>",
    locale: "<locale-string>",  # eg: "en-GB",
    ...
  }
...
```

I'd like to update to the latest Contentful version, but my system is reliant on these fields.

Can these fields be returned to the `Contentful.Entry`/`Contentful.Asset` or `Contentful.SysData` structs?

**Comment by floriank** [comment]
Absolutely.

thanks for reporting!
