### ISSUE TITLE
Examples in docs are displaying malformed

### ISSUE THREAD

**Issue by OldhamMade** [contentful-labs/contentful.ex#75]
Example here: https://hexdocs.pm/contentful/Contentful.Delivery.ContentTypes.html

<img width="870" alt="Screen Shot 2021-02-05 at 19 52 34" src="https://user-images.githubusercontent.com/111193/107076419-b36a5d80-67eb-11eb-8e2e-eeb9a5f2e96a.png">

**Comment by floriank** [comment]
Thank you for reporting!

I will take a look!
