### ISSUE TITLE
Hardcoded end point

### ISSUE THREAD

**Issue by zaeemarshad** [contentful-labs/contentful.ex#9]
The endpoint is hard-coded to cdn.contentful.com which only shows entries that have been published. By making it a run-time config, one can set the endpoint to preview.contentful.com and retrieve entries that are in draft state.

**Comment by dlitvakb** [comment]
Hey @zaeemarshad, my Elixir knowledge is not that much, could you consider making a PR to make it configurable but keeping the interface as is?

Cheers

**Comment by zaeemarshad** [comment]
So I have refactored the code a bit and split it into two modules i.e. Delivery and Preview to represent the endpoints. The interface is the same except that the functions have been moved to Contentful.Functions. I have yet to add tests for preview which I shall do soon time permitting.

**Comment by floriank** [comment]
I have actually not forgotten about this and will enter a `Contentful.Preview` module that can be used with the Query DSL, see attached PR.
